package br.com.munizsoares.util;

public enum Constante {


    PRODUTO_REGISTRADO("PRODUTO REGISTRADO COM SUCESSO !"),
    ERRO_VERIFICACAO_JWT("ERRO AO GERAR AO VERIFICAR O JWT"),
    ERRO_TOKEN("ERRO AO GERAR O TOKEN"),
    PROCESSAMENTO_DE_PEDIDO("PROCESSAMENTO DE NOVO PEDIDO"),
    CATEGORIA_NAO_ENCONTRADO("CATEGORIA NÃO ENCONTRADO"),
    PRODUTO_NAO_ENCONTRADO("PRODUTO NÃO ENCONTRADO"),
    PRODUTO_DELETADO("PRODUTO FOI DELETADO COM SUCESSO!"),
    PRECO_PRODUTO_NAO_INFORMADO("PREÇO DO PRODUTO NÃO FOI INFORMADO"),
    NOME_PRODUTO_NAO_INFORMADO("NOME DO PRODUTO NÃO FOI INFORMADA"),
    CATEGORIA_PRODUTO_NAO_INFORMADA("CATEGORIA DO PRODUTO NÃO FOI INFORMADA"),
    ID_NAO_INFORMADO("O ID não foi informado !"),
    NOME_NAO_INFORMADO("O Nome não foi informado !"),
    EMAIL_NAO_INFORMADO("O Email não foi informado !"),
    SENHA_NAO_INFORMADO("A Senha não foi informada !");


    private String valor;

    Constante(String valor) {
        this.valor = valor;
    }

    public String getValor() {
        return valor;
    }
}
